version: '3'

services:

  # php7-apache
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./src/:/var/www
      - ./resources/logs/web:/var/log/apache2/
    links:
      - db:db
    env_file:
      .env
    restart: always
    container_name: web_app

  # mysql
  db:
    image: mysql
    ports:
      - ${MYSQL_PORT}:3306
    env_file:
      .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./resources/logs/db:/var/log/mysql
    container_name: web_db

volumes:
  db_data:
